version: "3.7"

services:
  app:
    build: .
    ports:
      - "5000:5000"
    env_file: .env
    depends_on:
      - db
      - pgadmin
  db:
    container_name: postgres_container
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: fastify
      PGDATA: /var/lib/postgersql/data
    volumes:
      - ./postgresData:/var/lib/postgersql/data
    ports:
      - "5432:5432"
    networks:
      - postgres
    restart: unless-stopped
  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: parhamkhoram58@gmail.com
      PGADMIN_DEFAULT_PASSWORD: 1111
      PGADMIN_CONFIG_SERVER_MODE: "False"
    ports:
      - 5050:80
    volumes:
      - ./pgadmin:/var/lib/pgadmin
    networks:
      - postgres
    restart: unless-stopped
networks:
  postgres:
    driver: bridge
volumes:
  postgresData:
    driver: local
  pgadmin:
    driver: bridge
